#!/bin/bash
#SBATCH --job-name="124p4"
#SBATCH --output="124p4.%j.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=80G
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH -A umn120

echo "-------------------------------------------------------------------------"
echo "Environment for building and running applications with Intel compiler and MPI"

# Reset modules to base state
#module purge

#Load modules for Intel & MPI
module load cpu
module load intel mvapich2
module load slurm
module load fftw
#module list
#cd /home/evitral/sma-dft/quasi/

echo " "
echo "-------------------------------------------------------------------------"
echo "Application with double precision MPI parallel FFTW 3.3"
#export BUILD=/opt/fftw/3.3.8/intel/mvapich2_ib
export LIBS="-lfftw3_mpi -lfftw3 -lm -Wall -std=c++11"
mpicxx -O3 -o compressible/compressible-layer compressible/compressible-layer.cpp $LIBS
srun -n 16 ./compressible/compressible-layer 1000 800 124 0 > /expanse/lustre/projects/umn120/evitral/substrate/channel-124p4.out
