#!/bin/bash
#SBATCH --job-name="st126-85"
#SBATCH --output="st126-85.%j.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=80G
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH -A umn120

echo "-------------------------------------------------------------------------"
echo "Environment for building and running applications with Intel compiler and MPI"

# Reset modules to base state
#module purge

#Load modules for Intel & MPI
module load cpu/0.15.4
module load intel/19.1.1.217
module load mvapich2/2.3.4
module load slurm
module load fftw/3.3.8
#module list
#cd /home/evitral/sma-dft/quasi/

echo " "
echo "-------------------------------------------------------------------------"
echo "Application with double precision MPI parallel FFTW 3.3"
#export BUILD=/opt/fftw/3.3.8/intel/mvapich2_ib
export LIBS="-lfftw3_mpi -lfftw3 -lm -Wall -std=c++11"
mpicxx -O3 -o compressible/compressible compressible/compressible.cpp $LIBS
srun -n 16 ./compressible/compressible 1000 850 126 1 > /expanse/lustre/projects/umn120/evitral/compressible/stretch-6d2-5d2-fc126-85.out
