#!/bin/bash
#SBATCH -J stb2Q0d5phi0d1nu0d1
#SBATCH -o stb2Q0d5phi0d1nu0d1.%j.out
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=120G
#SBATCH --export=ALL
#SBATCH -t 00:10:00
#SBATCH -A umn120

echo "-------------------------------------------------------------------------"
echo "Environment for building and running applications with Intel compiler and MPI"

# Reset modules to base state
#module purge

#Load modules for Intel & MPI
module load intel/2018.1.163 mvapich2_ib
module load fftw
#module list
#cd /home/evitral/sma-dft/quasi/

echo " "
echo "-------------------------------------------------------------------------"
echo "Application with double precision MPI parallel FFTW 3.3"
export BUILD=/opt/fftw/3.3.8/intel/mvapich2_ib
export LIBS="-lfftw3_mpi -lfftw3 -lm -Wall -std=c++11"
mpicxx -I $BUILD/include -O3 -o quasi/quasi-stb quasi/quasi-stb.cpp -L $BUILD/lib $LIBS
ibrun -np 16 ./quasi/quasi-stb 1 9 340 0 > /oasis/scratch/comet/evitral/temp_project/quasi_stb/adv/result-stb.out
