#!/bin/bash
#SBATCH -J qe0d675nw8nu10000
#SBATCH -o qe0d675nw8nu10000.%j.out
#SBATCH --partition=compute
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=24
#SBATCH --mem=80G
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH -A umn120

echo "-------------------------------------------------------------------------"
echo "Environment for building and running applications with Intel compiler and MPI"

# Reset modules to base state
#module purge

#Load modules for Intel & MPI
module load intel
module load mvapich2_ib fftw
#module list
#cd /home/evitral/sma-dft/quasi/

echo " "
echo "-------------------------------------------------------------------------"
echo "Application with double precision MPI parallel FFTW 3.3"
export BUILD=/opt/fftw/3.3.8/intel/mvapich2_ib
export LIBS="-lfftw3_mpi -lfftw3 -lm -Wall -std=c++11"
mpicxx -I $BUILD/include -O3 -o quasi/quasi quasi/quasi.cpp -L $BUILD/lib $LIBS
ibrun -np 128 ./quasi/quasi 10000 675 140 0 > /oasis/scratch/comet/evitral/temp_project/quasi_compare/resultNw8-nu10000-e0d675.out
